spring.application.name=jpa
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/prueba_jpa?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=adjgc
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
